### ISSUE TITLE
Test existing RTs under UFS with the changes done in FV3 and CCPP/Physics

### ISSUE THREAD

**Issue by uturuncoglu** [esmf-org/noahmp#10]
The RTs need to be tested to be sure that the changes done for external land coupling does not break anything

**Comment by uturuncoglu** [comment]
Following RTs are tested:

- cpld_restart_p8(incl. cpld_control_p8) is tested and the test is passed
- control_restart_p8 (incl. control_p8) is tested and control_restart_p8 is failed. We were applying some changes for the consistency of the orography files and they were moved from coupled control case to match with the static files.  I send a message to Jun about it. So, somehow this change creating issue in the restart run.

**Comment by uturuncoglu** [comment]
All the regression test are run and issues are fixed. I am plaining to create UFS Weather model PR (incl. PRs for sub-components) and update the model and test it again.

**Comment by danrosen25** [comment]
Waiting on https://github.com/NOAA-EMC/CDEPS/pull/50 and https://github.com/ufs-community/ufs-weather-model/pull/1443

**Comment by uturuncoglu** [comment]
This is completed. The PR is merged.
