### ISSUE TITLE
Validate DATM->LND runs against UFS land driver

### ISSUE THREAD

**Issue by rsdunlapiv** [esmf-org/noahmp#3]

**Comment by rsdunlapiv** [comment]
#4 will facilitate this task.

**Comment by uturuncoglu** [comment]
As we discussed in the last noahmp call, I created hourly forcing files (1d vector format) for Michael to test under ufs-land-driver. Still waiting response from him.

**Comment by danrosen25** [comment]
Michael is preparing forcing data in a premade run directory.

**Comment by uturuncoglu** [comment]
I got the test case from Michael and start to work on modifying forcing fields.

**Comment by uturuncoglu** [comment]
Still working on it. There is an issue in the initialization that leads to the large difference at the beginning. We are trying to resolve it by updating the initial conditions.

**Comment by uturuncoglu** [comment]
This is done. CDEPS provided ERA5 data stream under UFS Weather Model is validated with ufs-land-driver.
